# from gitlab:
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

#image: danwos/sphinxneeds-latexpdf:latest
#image: danwos/sphinxneeds:latest
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version ; whoami # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install setuptools
  # install script requirements
  # pip install -r ./requirements.txt
  - apt update
  - apt-get --yes install graphviz default-jdk



pages:
  stage: deploy
  script:
    # install documentation requirements
    - pip install -r ./docs/requirements.txt
    #disabled -W
    - sphinx-build -b html -t project_b ./docs ./public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

